### ISSUE TITLE
Game Crashed When Use Modern-Dynamics

### ISSUE THREAD

**Issue by link-fgfgui** [Technici4n/Modern-Dynamics#111]
When I use Modern-Dynamics transport `Hephaestus`'s fluid ,the game crashed.
I can't enter the world again.

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-05-24 22:37:05
Description: Ticking pipe network

java.lang.RuntimeException: Encountered an exception while invoking a transaction outer close callback.
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.close(TransactionManagerImpl.java:159)
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.commit(TransactionManagerImpl.java:186)
	at dev.technici4n.moderndynamics.network.fluid.FluidCache.doTick(FluidCache.java:151)
	at dev.technici4n.moderndynamics.network.NetworkCache.tick(NetworkCache.java:72)
	at dev.technici4n.moderndynamics.network.NetworkManager.onEndTick(NetworkManager.java:59)
	at dev.technici4n.moderndynamics.ModernDynamics.lambda$onInitialize$2(ModernDynamics.java:53)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43)
	at net.minecraft.server.MinecraftServer.handler$dke000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:7862)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.handler$bmk000$carpet$modifiedRunLoop(MinecraftServer.java:14942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.remove(ArrayList.java:504)
	at slimeknights.tconstruct.smeltery.block.entity.tank.SmelteryTank$FluidStackSlot.lambda$extract$2(SmelteryTank.java:361)
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.close(TransactionManagerImpl.java:156)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.close(TransactionManagerImpl.java:159)
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.commit(TransactionManagerImpl.java:186)
	at dev.technici4n.moderndynamics.network.fluid.FluidCache.doTick(FluidCache.java:151)

-- Network details --
Details:
	Level: minecraft:overworld
	Number of nodes: 3
Stacktrace:
	at dev.technici4n.moderndynamics.network.NetworkCache.tick(NetworkCache.java:72)
	at dev.technici4n.moderndynamics.network.NetworkManager.onEndTick(NetworkManager.java:59)
	at dev.technici4n.moderndynamics.ModernDynamics.lambda$onInitialize$2(ModernDynamics.java:53)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43)
	at net.minecraft.server.MinecraftServer.handler$dke000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:7862)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.handler$bmk000$carpet$modifiedRunLoop(MinecraftServer.java:14942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Details of first node in the network --
Details:
	Name: moderndynamics:fluid_pipe // dev.technici4n.moderndynamics.pipe.FluidPipeBlockEntity
	Block: Block{moderndynamics:fluid_pipe}[waterlogged=false]
	Block location: World: (0,-59,-5), Section: (at 0,5,11 in 0,-4,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block: Block{moderndynamics:fluid_pipe}[waterlogged=false]
	Block location: World: (0,-59,-5), Section: (at 0,5,11 in 0,-4,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at dev.technici4n.moderndynamics.network.NetworkCache.tick(NetworkCache.java:72)
	at dev.technici4n.moderndynamics.network.NetworkManager.onEndTick(NetworkManager.java:59)
	at dev.technici4n.moderndynamics.ModernDynamics.lambda$onInitialize$2(ModernDynamics.java:53)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43)
	at net.minecraft.server.MinecraftServer.handler$dke000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:7862)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.handler$bmk000$carpet$modifiedRunLoop(MinecraftServer.java:14942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.7, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1395279488 bytes (1330 MiB) / 3888119808 bytes (3708 MiB) up to 6874464256 bytes (6556 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12450H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x46a3
	Graphics card #0 versionInfo: DriverVersion=31.0.101.3688
	Graphics card #1 name: NVIDIA GeForce RTX 4050 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x28a1
	Graphics card #1 versionInfo: DriverVersion=31.0.15.5152
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20474.30
	Virtual memory used (MB): 16454.91
	Swap memory total (MB): 4352.00
	Swap memory used (MB): 303.54
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn3276m -Xmx6553m
	Fabric Mods: 
		ad_astra: Ad Astra 1.15.18
			javazoom_jlayer: jlayer 1.0.1
		ad_astra_giselle_addon: Ad Astra: Giselle Addon 6.7
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		ae2: Applied Energistics 2 15.2.0
			team_reborn_energy: Energy 3.0.0
		ae2-emi-crafting: AE2 EMI Crafting Integration 1.3.1
		ae2wtlib: AE2WTLib 15.2.1-fabric
		alwaysloaded: Always Loaded Mod 1.1.1
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		attributefix: AttributeFix 21.0.4
		automaticdoors: Automatic Doors 4.6
		balm-fabric: Balm 7.2.2
		betterfpsdist: Better FPS distance Mod 1.20.1-4.3
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 3.9.7+fabric-1.20.1
			tcdcommons: TCD Commons API 3.9.6+fabric-1.20.1
		bettertrims: BetterTrims 2.3.1
			mixinsquared: MixinSquared 0.1.1
		block_beams: Block Beams 1.0.1
		bookshelf: Bookshelf 20.1.10
		boostedbrightness: Boosted Brightness 2.2.0
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		botania: Botania 1.20.1-444-FABRIC
			fiber: fiber 0.23.0-2
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		botarium: Botarium 2.3.3
		breakfree: Break Free 1.2.0
		carpet: Carpet Mod 1.4.112+v230608
		chesttracker: Chest Tracker 1.1.23
			whereisit: Where Is It 1.14.17
		clearview: Lava Clear View 7.0.0
		clientcommands: Client Commands 2.8.5
			betterconfig: BetterConfig 1.2.1
			clientarguments: clientarguments 1.5
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.60
		connectivity: Connectivity Mod 1.20.1-5.5
		continuity: Continuity 3.0.0-beta.5+1.20.1
		controlling: Controlling For Fabric 12.0.2
		cookingforblockheads: Cooking for Blockheads 16.0.4
		coxinhautilities: Coxinha Utilities 1.4.13+1.20.1
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_tags: Porting Lib Tags 3.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
		create_jetpack: Create Jetpack 4.2.0
			flightlib: Flight Lib 2.1.0
		create_structures: Create: Structures 1.1.0
		createaddition: Create Crafts & Additions 1.2.3
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		cull-less-leaves: Cull Less Leaves 1.3.0
		cupboard: cupboard 1.20.1-2.6
		customskinloader: CustomSkinLoader 14.19.1
		dark-loading-screen: Dark Loading Screen 1.6.14
		darkutils: DarkUtilities 17.0.3
		datapackportals: Datapack Portals 1.2.3-1.20
			customportalapi: Custom Portal Api 0.0.1-beta64-1.20
		debugify: Debugify 1.20.1+2.0
		delightfulcreators: Delightful Creators 1.1.8
		disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		doubledoors: Double Doors 5.7
		dynamic_fps: Dynamic FPS 3.4.3
		emi: EMI 1.1.6+1.20.1+fabric
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		extended_drawers: Extended Drawers 2.1.1+mc.1.20.1
			config_toolkit: ConfigToolkit 1.0.0
				io_determann_shadow-api-17: shadow-api-17 0.1.1
				net_fabricmc_javapoet: javapoet 0.1.0
			graphlib: Graph Lib 1.4.0+1.20
				kmodlib-overlay: KModLib Overlay 0.2.12+1.20
				libnetworkstack: Lib Network Stack 0.10.0
			noindium: No Indium? 1.1.0+1.20
		extendedae: ExtendedAE 1.20-1.0.1-fabric
			configuration: Configuration 2.2.0
		extra-mod-integrations: Extra Mod Integrations 0.4.5+1.20.1
		extractinator: Extractinator 2.3.0
		fabric-api: Fabric API 0.92.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		farmingforblockheads: Farming for Blockheads 14.0.2
		fdjei: Just Enough Farmer's Recipes 1.0.1
		ferritecore: FerriteCore 6.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		ftblibrary: FTB Library 2001.2.2
		ftbultimine: FTB Ultimine 2001.1.5
		gca: GugleCarpetAddition mc1.20.1-2.8.0+build.42
		gpumemleakfix: Gpu memory leak fix mod 1.20.1-1.8
		harvestwithease: Harvest with ease 8.0.1.0
		i18nupdatemod: I18nUpdateMod 3.5.5
		identifier_translation: 标识符翻译 3_1.20-1.20.1
		indium: Indium 1.0.30+mc1.20.4
		ingameime: ContingameIME 1.0.7-1.20.1
		inventoryessentials: Inventory Essentials 8.2.3
		inventorysorter: Inventory Sorter 1.9.0-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		ironchest: Iron Chests 2.0.2
			libgui: LibGui 8.1.1+1.20.1
				jankson: Jankson 6.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
		jade: Jade 11.9.2+fabric
		jadeaddons: Jade Addons 5.2.5
		jamd: Just Another Mining Dimension 3.4.2+mc1.20.1
		java: OpenJDK 64-Bit Server VM 17
		jecharacters: Just Enough Characters 4.5.4
		jei: Just Enough Items 15.3.0.4
		jeresources: Just Enough Resources 1.4.0.247
		kibe: Kibe 1.10.1-BETA+1.20
			playerabilitylib: Pal 1.8.0
		ksyxis: Ksyxis 1.3.1
		lazydfu: LazyDFU 0.1.3
		logical_zoom: Logical Zoom 0.0.20
		mcwifipnp: LAN World Plug-n-Play 1.6.9
		memoryleakfix: Memory Leak Fix 1.1.5
		merequester: ME Requester 1.20.1-1.1.4
			midnightlib: MidnightLib 1.2.1
		minecraft: Minecraft 1.20.1
		moderndynamics: Modern Dynamics 0.7.0-beta
		modernfix: ModernFix 5.17.0+mc1.20.1
		modernui: Modern UI 3.10.1.4
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.7
			com_vladsch_flexmark_flexmark: flexmark 0.64.8
			com_vladsch_flexmark_flexmark-util-ast: flexmark-util-ast 0.64.8
			com_vladsch_flexmark_flexmark-util-builder: flexmark-util-builder 0.64.8
			com_vladsch_flexmark_flexmark-util-collection: flexmark-util-collection 0.64.8
			com_vladsch_flexmark_flexmark-util-data: flexmark-util-data 0.64.8
			com_vladsch_flexmark_flexmark-util-dependency: flexmark-util-dependency 0.64.8
			com_vladsch_flexmark_flexmark-util-format: flexmark-util-format 0.64.8
			com_vladsch_flexmark_flexmark-util-html: flexmark-util-html 0.64.8
			com_vladsch_flexmark_flexmark-util-misc: flexmark-util-misc 0.64.8
			com_vladsch_flexmark_flexmark-util-sequence: flexmark-util-sequence 0.64.8
			com_vladsch_flexmark_flexmark-util-visitor: flexmark-util-visitor 0.64.8
		modmenu: Mod Menu 7.2.2
		mr_hero_proof: Hero Proof 5.1.2
		nbt_ac: NBT Autocomplete 1.2.1
		nerb: Not Enough Recipe Book 0.3
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		nounusedchunks: No Unused Chunks 2.0
		openloader: OpenLoader 19.0.3
		passivesearchbar: PassiveSearchBar 1.0.0
		patchouli: Patchouli 1.20.1-84-FABRIC
		polymorph: Polymorph 0.49.3+1.20.1
			cardinal-components-block: Cardinal Components API (blocks) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
			spectrelib: SpectreLib 0.13.15+1.20.1
		porting_lib: Porting Lib 2.3.4+1.20.1
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_asm: Porting Lib ASM 2.3.4+1.20.1
			porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
			porting_lib_blocks: Porting Lib Blocks 2.3.4+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.4+1.20.1
			porting_lib_chunk_loading: Porting Lib Chunk Loading 2.3.4+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.4+1.20.1
			porting_lib_common: Porting Lib Common 2.3.4+1.20.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_data: Porting Lib Data 2.3.4+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
			porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
			porting_lib_gametest: Porting Lib GameTest 2.3.4+1.20.1
			porting_lib_gui_utils: Porting Lib Gui Utils 2.3.4+1.20.1
			porting_lib_items: Porting Lib Items 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_level_events: Porting Lib Level Events 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
			porting_lib_model_builders: Porting Lib Model Builders 2.3.4+1.20.1
			porting_lib_model_generators: Porting Lib Model Generators 2.3.4+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.3.4+1.20.1
			porting_lib_model_materials: Porting Lib Model Materials 2.3.4+1.20.1
			porting_lib_models: Porting Lib Models 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_registries: Porting Lib Registries 2.3.4+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
			porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
		powah: Powah! 5.0.5
		redirector: Redirector 1.20.1-4.4.0
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.25
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		searchables: Searchables 1.0.3
		sodium: Sodium 0.5.8+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		spawnermod: Enhanced Mob Spawners 1.2.6
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		tabtps-fabric: TabTPS 1.3.18
			adventure-platform-fabric: adventure-platform-fabric 5.10.0-SNAPSHOT
				net_kyori_adventure-api: adventure-api 4.14.0
				net_kyori_adventure-key: adventure-key 4.14.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.0
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.14.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.14.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.14.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.14.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.14.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.14.0
				net_kyori_ansi: ansi 1.0.1
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			cloud: Cloud 1.8.3
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.8.3
				cloud_commandframework_cloud-core_: cloud-core 1.8.3
				cloud_commandframework_cloud-services_: cloud-services 1.8.3
				fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
				io_leangen_geantyref_geantyref: geantyref 1.3.13
			cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.8.3
			com_typesafe_config: config 1.4.2
			net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.14.0
			net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
			net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.14.0
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		talkbubbles: Talk Bubbles 1.0.8
		tamago: Tamago 3.0
		taxfreelevels: Tax Free Levels 1.3.12
		tconstruct: Hephaestus 1.20.1-3.6.4.273
			mantle: Mantle 1.20.1-1.9.268
				cardinal-components-base: Cardinal Components API (base) 5.2.2
				cardinal-components-entity: Cardinal Components API (entities) 5.2.2
				star: Star 1.5.1+1.20.1
		tiefix: TieFix 1.14.0
		toms_storage: Tom's Simple Storage Mod 1.6.6
		tooltipfix: ToolTip Fix 1.1.1-1.20
		tooltiptooltips: Tooltip Tool Tips 1.1.0
		torcherino: Torcherino 20.0.0
		trashcans: Trash Cans 1.0.18
		travelerstitles: Traveler's Titles 1.20-Fabric-4.0.2
			org_reflections_reflections: reflections 0.10.2
		traverse: Traverse 7.0.11
			biolith: Biolith 1.0.0-beta.1
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 7.0.3
			terraform-config-api-v1: Terraform Config API (v1) 7.0.3
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.3
			terraform-tree-api-v1: Terraform Tree API (v1) 7.0.3
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.3
			traverse-client: Traverse: Client 7.0.11
			traverse-common: Traverse: Common 7.0.11
			traverse-worldgen: Traverse: World Generation 7.0.11
		trenzalore: Trenzalore 3.3.10
			com_unrealdinnerbone_unrealconfig-core: UnRealConfig-core 12.3.4
			com_unrealdinnerbone_unrealconfig-gson: UnRealConfig-gson 12.3.4
		trinkets: Trinkets 3.7.2
		villagespawnpoint: Village Spawn Point 4.2
		vmp: Very Many Players 0.2.0+beta.7.102
		wands: Building Wands 2.6.9-release
		wirelessnetworks: Wireless Networks 1.7.1
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		xaerominimap: Xaero's Minimap 24.1.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.4.2+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.5
			org_javassist_javassist: javassist 3.29.2-GA
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['fgfgui_link'/628, l='ServerLevel[TEST]', x=1.63, y=-60.00, z=-3.77]]
	Data Packs: vanilla, fabric, data/CreateOriginModify, data/JK_BoxMover-1.20
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: ATM-L-Fabric-1.20.1
```

**Comment by Technici4n** [comment]
That looks like a tinker's construct bug.

**Comment by link-fgfgui** [comment]
OK, Thank you
