### ISSUE TITLE
[1.20.1] Fails to save chunk with C2ME

### ISSUE THREAD

**Issue by amyavi** [Technici4n/Modern-Dynamics#114]
Minecraft version: 1.20.1 (Fabric Loader 0.15.11)
Mod version: 0.7.0-beta

When using the pipe block with C2ME installed, sometimes the chunk fails to save (gets rolled back) and this is logged to console:
```
[23:38:21] [C2ME worker #2/ERROR]: Failed to save chunk -99,-56 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.IdentityHashMap$KeySet.toArray(IdentityHashMap.java:1031) ~[?:?]
        at java.util.IdentityHashMap$KeySet.toArray(IdentityHashMap.java:1016) ~[?:?]
        at java.util.Collections$SetFromMap.toArray(Collections.java:5687) ~[?:?]
        at java.util.ArrayList.<init>(ArrayList.java:181) ~[?:?]
        at dev.technici4n.moderndynamics.network.NetworkManager.updateNetworks(NetworkManager.java:172) ~[Modern-Dynamics-0.7.0-beta.jar:?]
        at dev.technici4n.moderndynamics.network.NetworkManager.findNode(NetworkManager.java:163) ~[Modern-Dynamics-0.7.0-beta.jar:?]
        at dev.technici4n.moderndynamics.network.NodeHost.findNode(NodeHost.java:151) ~[Modern-Dynamics-0.7.0-beta.jar:?]
        at dev.technici4n.moderndynamics.network.NodeHost.separateNetwork(NodeHost.java:156) ~[Modern-Dynamics-0.7.0-beta.jar:?]
        at dev.technici4n.moderndynamics.pipe.PipeBlockEntity.toTag(PipeBlockEntity.java:168) ~[Modern-Dynamics-0.7.0-beta.jar:?]
        at dev.technici4n.moderndynamics.MdBlockEntity.method_11007(MdBlockEntity.java:75) ~[Modern-Dynamics-0.7.0-beta.jar:?]
        at net.minecraft.class_2586.method_38244(class_2586.java:84) ~[server-intermediary.jar:?]
        at net.minecraft.class_2586.method_38242(class_2586.java:64) ~[server-intermediary.jar:?]
        at net.minecraft.class_2852.redirect$bhh000$c2me-threading-chunkio$onChunkGetPackedBlockEntityNbt(class_2852.java:3109) ~[server-intermediary.jar:?]
        at net.minecraft.class_2852.method_12410(class_2852.java:328) ~[server-intermediary.jar:?]
        at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.5-26f4ad93b9b74419.jar:?]
        at net.minecraft.class_3898.md22b5fa$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:12262) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
```

**Comment by JSP1408** [comment]
brainrot ahhhh developer
