### ISSUE TITLE
IAE Amount may not be negative, but it is: -8192

### ISSUE THREAD

**Issue by suerion** [Technici4n/Modern-Dynamics#76]
Hey, we got an error on our side, i hope i could help you to find the issue:

```
java.lang.IllegalArgumentException: Amount may not be negative, but it is: -8192
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.insert(CombinedStorage.java:62)
	at dev.technici4n.moderndynamics.network.item.SimulatedInsertionTarget.insert(SimulatedInsertionTarget.java:57)
	at dev.technici4n.moderndynamics.network.item.ItemCache.insertList(ItemCache.java:78)
	at dev.technici4n.moderndynamics.network.item.ItemHost.lambda$buildExtractorNetworkInjectStorage$1(ItemHost.java:125)
	at net.fabricmc.fabric.api.transfer.v1.storage.StorageUtil.move(StorageUtil.java:105)
	at dev.technici4n.moderndynamics.network.item.ItemHost.tickAttachments(ItemHost.java:187)
	at dev.technici4n.moderndynamics.network.item.ItemCache.doTick(ItemCache.java:49)
	at dev.technici4n.moderndynamics.network.NetworkCache.tick(NetworkCache.java:69)
	at dev.technici4n.moderndynamics.network.NetworkManager.onEndTick(NetworkManager.java:59)
	at dev.technici4n.moderndynamics.ModernDynamics.lambda$onInitialize$2(ModernDynamics.java:53)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62)
	at net.minecraft.server.MinecraftServer.handler$chb002$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:6821)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

```

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2885193384 bytes (2751 MiB) / 15586033664 bytes (14864 MiB) up to 21307064320 bytes (20320 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7280
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 75171.64
	Virtual memory used (MB): 28577.50
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 28.29
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx20320m -Xms256m
	Fabric Mods: 
		adorn: Adorn 3.8.3+1.19.2
		ae2: Applied Energistics 2 12.9.3
			noindium: No Indium? 1.1.0+1.19
		alternate-current: Alternate Current 1.5.0
		another_furniture: Another Furniture 2.1.2-1.19.2
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.5.82
		archon: Archon 0.5.0
			omega-config: OmegaConfig 1.2.3-1.18.1
		automodpack: AutoModpack 3.3.0
		bclib: BCLib 2.1.6
		betterend: Better End 2.1.4
		betterf3: BetterF3 4.0.0
		betterfpsdist: Better FPS distance Mod 1.19-2.4
		betternether: Better Nether 7.1.3
		bookshelf: Bookshelf 16.2.18
		borderlessmining: Borderless Mining 1.1.5+1.19
		botania: Botania 1.19.2-438-FABRIC
			fiber: fiber 0.23.0-2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		botanypots: BotanyPots 9.0.33
		botanytrees: BotanyTrees 5.0.4
		bugjump: BugJump 1.0.0-1.19.2
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		continuity: Continuity 2.0.2+1.19
		create: Create 0.5.0.i-1003+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.8.a-4
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.926+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.926+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.926+1.19.2
				porting_lib_base: Porting Lib Base 2.1.926+1.19.2
				porting_lib_common: Porting Lib Common 2.1.926+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.926+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.926+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.926+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.926+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.926+1.19.2
				porting_lib_loot: Porting Lib Loot 2.1.926+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.926+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.926+1.19.2
				porting_lib_models: Porting Lib Models 2.1.926+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.926+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.926+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.926+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			registrate-fabric: Registrate for Fabric 1.1.57-MC1.19.2
		createdeco: Create Deco 1.3.2-1.19.2
		createreibugfix: CreateFabric&REIBugFix 0.1.2-mc1.19.x
		cull-less-leaves: Cull Less Leaves 1.0.6
			conditional-mixin: conditional mixin 0.3.0
		cullclouds: Cull Clouds 0.1.0
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		decorative_blocks: Decorative Blocks 3.0.0
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		easymagic: Easy Magic 4.3.3
		elytraslot: Elytra Slot 6.1.1+1.19.2
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		exlinefurniture: Exline's Furniture 2.3.2
		extended_drawers: Extended Drawers 1.3.10+mc.1.19.2
			graphlib: Graph Lib 0.3.6+1.19.2
			mconfig: Mconfig 1.2.0+mc.1.19-rc1
				de_poiu_apron_apron: apron 2.1.1
				fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-furnaces: Fabric Furnaces 2.2.0-1.19.2
		fabric-language-kotlin: Fabric Language Kotlin 1.9.4+kotlin.1.8.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.19
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmersknives: Farmer's Knives 2.4
		farsight: Farsight Mod 1.19-2.4
			com_github_jctools_jctools_jctools-core: jctools-core v4.0.1
		forgeconfigapiport: Forge Config API Port 4.2.11
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
				mm: Manningham Mills 2.3
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		ftbchunks: FTB Chunks 1902.3.21-build.266
		ftblibrary: FTB Library 1902.3.18-build.208
		ftbteams: FTB Teams 1902.2.13-build.100
		furnitureexpanded: Furniture Expanded [FABRIC] 1.0.2-1.19.2
		fwaystones: Fabric Waystones 3.0.7+mc1.19.2
		grindenchantments: Grind Enchantments 2.0.0+1.19.2
		icarus: Icarus 1.14
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.6.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre12
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jade: Jade 8.7.3
		jadeaddons: Jade Addons 3.1.0
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.6
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		kibe: Kibe 1.9.11-BETA+1.19
			playerabilitylib: Pal 1.6.0
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		languagereload: Language Reload 1.5.6+1.19.2
		lithium: Lithium 0.11.1
		macawsbridgesbyg: Macaw's Bridges - BYG 1.19.2-1.2
		mcda: MC Dungeons Armors 2.4.4
		mcdar: MC Dungeons Artifacts 1.5.3-1.19
		mcdw: MC Dungeons Weapons 5.0.8-1.19
			enchant_giver: Enchant Giver 1.3.0
		mcwbridges: Macaw's Bridges 2.0.7
		mcwdoors: Macaw's Doors 1.0.8
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwfurnitures: Macaw's Furniture 3.1.0
		mcwlights: Macaw's Lights and Lamps 1.0.5
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.2
		mcwroofs: Macaw's Roofs 2.2.3
		mcwtrpdoors: Macaw's Trapdoors 1.0.9
		mcwwindows: Macaw's Windows 2.1.2
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		mixintrace: MixinTrace 1.1.1+1.17
		moderndynamics: Modern Dynamics 0.5.0-beta
			team_reborn_energy: Energy 2.2.0
		modmenu: Mod Menu 4.2.0-beta.2
		moonlight: Moonlight 1.19.2-2.2.31
		mousewheelie: Mouse Wheelie 1.10.7+mc1.19.2
			amecsapi: Amecs API 1.3.7+mc22w17a
			coat: Coat 1.0.0-beta.19+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.3+mc22w17a
		multisleep: Multiplayer Sleep 1.4
			libgui: LibGui 6.3.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		owo: oωo 0.8.5+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-77-FABRIC
		pfm: Paladin's Furniture 1.1.1
		polylib: PolyLib 1900.0.2-build.73
		powah: Powah! 4.0.10
		puzzleslib: Puzzles Lib 4.4.0
		recipecache: recipecache 0.2.0-1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		roughlyenoughitems: Roughly Enough Items 9.1.595
			error_notifier: Error Notifier 1.0.9
		smoke_suppression: Smoke Suppression 1.0.13
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		supplementaries: Supplementaries 1.19.2-2.3.10
		terrablender: TerraBlender 2.0.1.136
		timeoutout: TimeOut Out 1.0.3+1.19.1
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.19
		trinkets: Trinkets 3.4.2
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		v_slab_compat: v_slab_compat 1.19.2-1.4
		voicechat: Simple Voice Chat 1.19.2-2.4.7
		xaerominimap: Xaero's Minimap 23.4.1
		xlpackets: XLPackets 1.19.2-4
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yigd: You're in Grave Danger 1.4.9
		yosbr: YOSBR 0.1.1
		z_mcwfencesbyg: Macaw's Fences - BYG 1.19.2-1.0
		z_mcwroofsbyg: Macaw's Roofs - BYG 1.19.2-1.2
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['Kamitzu19'/564, l='ServerLevel[Sky Fabrik]', x=10328.30, y=85.90, z=3773.99]]
	Data Packs: vanilla, Fabric Mods, Supplementaries Generated Pack, V Slab Compat Generated Pack
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.19-1.19.2
```

**Comment by Technici4n** [comment]
Hello, this is probably caused by another mod saying it received more items that what the pipe gave it. For example the pipe asking "try to insert 4 diamonds" and the inventory responding "sure, I inserted 10", then the pipe ends up with negative amounts in its calculations that cause the crash.

Unfortunately, the error doesn't mention which block might be the problem, nor which pipe this is coming from.

**Comment by Technici4n** [comment]
Hi, I've just started the release process for version 0.5.1-beta which will include more info in the crash report. Please check with that installed (will be out in ~20 minutes).

**Comment by suerion** [comment]
Hey, we will test it tomorrow and i will come back with feedback. Thanks

**Comment by suerion** [comment]
we don't get any more issues from this error
